
CREATE PLUGGABLE DATABASE dev ADMIN USER supersystem IDENTIFIED BY "oracle" ROLES = (DBA);
CREATE PLUGGABLE DATABASE uat ADMIN USER supersystem IDENTIFIED BY "oracle" ROLES = (DBA);
CREATE PLUGGABLE DATABASE sit ADMIN USER supersystem IDENTIFIED BY "oracle" ROLES = (DBA);
CREATE PLUGGABLE DATABASE stg ADMIN USER supersystem IDENTIFIED BY "oracle" ROLES = (DBA);
CREATE PLUGGABLE DATABASE pro ADMIN USER supersystem IDENTIFIED BY "oracle" ROLES = (DBA);
CREATE PLUGGABLE DATABASE cer ADMIN USER supersystem IDENTIFIED BY "oracle" ROLES = (DBA);
alter pluggable database ORCLPDB open;
alter pluggable database DEV open;
alter pluggable database UAT  open;
alter pluggable database SIT open;
alter pluggable database STG open;
alter pluggable database pro open;
alter pluggable database cer open;
alter pluggable database ORCLPDB save state;
alter pluggable database DEV  save state;
alter pluggable database DEV save state;
alter pluggable database SIT save state;
alter pluggable database UAT save state;
alter pluggable database STG save state;
alter pluggable database PRO save state;
alter pluggable database CER save state;
alter session set container=ORCLPDB;
create directory REFRESH as '/refresh";
alter session set container=UAT;
create directory REFRESH as '/refresh";
grant read, write on directory REFRESH to PUBLIC;
alter session set container=SIT;
create directory REFRESH as '/refresh';
grant read, write on directory REFRESH to PUBLIC;
alter session set container=CER;
create directory REFRESH as '/refresh';
grant read, write on directory REFRESH to PUBLIC;
alter session set container=STG;
create directory REFRESH as '/refresh';
grant read, write on directory REFRESH to PUBLIC;
alter session set container=PRO;
create directory REFRESH as '/refresh';
grant read, write on directory REFRESH to PUBLIC;
alter session set container=DEV;
create directory REFRESH as '/refresh';
grant read, write on directory REFRESH to PUBLIC;